language: php

sudo: false

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.0
    - php: hhvm

branches:
  only:
    - 1.0

before_script:
  - composer self-update
  - composer install --dev --no-interaction

notifications:
  email:
    recipients:
      - kevinkhill@gmail.com
    on_success: change # default: change
    on_failure: always # default: always

script:
  - mkdir log
  - phpunit --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v
