language: php

php: 
  - 5.3
  - 5.4
  - 5.5

branches:
  only:
    - master

before_script:
  - composer self-update
  - composer install

notifications:
  email:
    recipients:
      - kevinkhill@gmail.com
    on_success: change # default: change
    on_failure: always # default: always

script:
  - mkdir log
  - phpunit

after_script:
  - php vendor/bin/coveralls
